baseURL = 'https://aitorguti.github.io/'
languageCode = 'en-us'
title = "Aitor's Cloud"
theme = 'hugo-theme-cleanwhite'
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = "UA-210096427-1"
preserveTaxonomyNames = true
paginate = 10 #frontpage pagination
hasCJKLanguage = true
enableEmoji = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "https://live.staticflickr.com/65535/52461746395_60a797166a_6k.jpg"
  SEOTitle = "Aitor's Cloud"
  description = "Aitor Gutierrez Valero"
  keyword = "Aitor, blog, Spain"
  slogan = ""

  image_404 = "img/404-bg.jpg"
  title_404 = "not found"
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Studying Chemistry at the University of Edinburgh"
  sidebar_avatar = "img/bw-self.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 0

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = false
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = false
  bookmarks = false
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = false 
  email          = "aitorg88@gmail.com"
  #facebook      = "https"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "https://twitter.com/"
  #linkedin       = "https://www.linkedin.com/"
  #stackoverflow  = "https://stackoverflow.com/users/"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/AitorGuti"
  #wechat         = "your wechat qr code image"
  #medium         = "https://medium.com/"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  # [[params.friend_link]]
  # title = "Linda的博客"
  # href =  "https://zhaozhihan.com"

  # [[params.bookmark_link]]
  # title =  "Martin Fowler"
  # href =  "https://martinfowler.com"
  # [[params.bookmark_link]]
  # title = "ServiceMesher"
  # href =  "http://www.servicemesher.com"
  # [[params.bookmark_link]]
  # title =  "Pxhere"
  # href = "https://pxhere.com"
  # [[params.bookmark_link]]
  # title = "unsplash"
  # href = "https://unsplash.com"
  
  #[[params.addtional_menus]]
  #title =  "BOOKS"
  #href =  "/top/books/"
  [[params.addtional_menus]]
  title =  "ARCHIVE"
  href =  "/top/archive/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
  [markup.highlight]
    style = "dracula"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
